# Generated by Django 3.2 on 2021-05-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='remove_pin',
            field=models.CharField(default='3671', max_length=10, null=True),
        ),
    ]
