# Generated by Django 3.2 on 2021-05-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_variation_remove_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='remove_pin',
            field=models.CharField(default='80693', max_length=10, null=True, unique=True),
        ),
    ]
