# Generated by Django 3.2 on 2021-05-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_variation_remove_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='remove_pin',
            field=models.CharField(default='67734', max_length=10, null=True, unique=True),
        ),
    ]
