# Generated by Django 3.2 on 2021-05-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210525_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='remove_pin',
            field=models.CharField(default='54673', max_length=10, null=True, unique=True),
        ),
    ]
