# Generated by Django 3.2 on 2021-05-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210529_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='remove_pin',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
