# Generated by Django 3.2 on 2021-05-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_variation_remove_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expire',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='expire',
            field=models.DateField(null=True),
        ),
    ]
