# Generated by Django 3.2 on 2021-05-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210530_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expire',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='variation',
            name='expire',
            field=models.CharField(default='', max_length=10),
        ),
    ]
