# Generated by Django 3.2 on 2021-06-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210530_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_honey_first',
            field=models.BooleanField(default=False),
        ),
    ]
