# Generated by Django 3.2 on 2021-06-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_user_is_honey_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
