# Generated by Django 3.2 on 2021-06-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20210602_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
