# Generated by Django 3.2 on 2021-06-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20210603_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='observation',
        ),
        migrations.AddField(
            model_name='order',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
