# Generated by Django 3.2 on 2022-07-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
