# Generated by Django 3.2 on 2022-07-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_product_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parecido',
            field=models.JSONField(default=list),
        ),
    ]
