# Generated by Django 3.2 on 2022-07-27 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_product_parecido'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedProducts', to='base.product'),
        ),
    ]
