# Generated by Django 3.2 on 2022-07-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_product_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test',
        ),
    ]
