# Generated by Django 3.2 on 2022-07-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_product_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='parecido',
            new_name='similar',
        ),
    ]
