# Generated by Django 3.2 on 2022-07-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_parecido_product_similar'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carac',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='como',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cuidados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ficha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='recomendacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
