# Generated by Django 3.2 on 2022-07-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20220727_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_categories',
            field=models.JSONField(default=list),
        ),
    ]
