# Generated by Django 3.2 on 2022-07-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_product_sub_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='higiene',
            field=models.TextField(blank=True, null=True),
        ),
    ]
