export const Bairros = [
  "Antares",
  "Barro Duro",
  "Bebedouro",
  "Benedito Bentes",
  "Bom Parto",
  "Chã de Bebedouro",
  "Centro",
  "Chã da Jaqueira",
  "Cidade Universitária",
  "Clima Bom",
  "Cruz das Almas",
  "Farol",
  "Feitosa",
  "Fernão Velho",
  "Garça Torta",
  "Gruta de Lourdes",
  "Guaxuma",
  "Ipioca",
  "Jacarecica",
  "Jacintinho",
  "Jaraguá",
  "Jardim Petrópolis",
  "Jatiúca",
  "Levada",
  "Mangabeiras",
  "Mutange",
  "Ouro Preto",
  "Pajuçara",
  "Pescaria",
  "Petrópolis",
  "Pinheiro",
  "Pitanguinha",
  "Ponta da Terra",
  "Ponta Grossa",
  "Ponta Verde",
  "Pontal da Barra",
  "Prado",
  "Riacho Doce",
  "Rio Novo",
  "Santa Amélia",
  "Santa Lúcia",
  "Santo Amaro",
  "Santos Dumont",
  "São Jorge",
  "Serraria",
  "Tabuleiro do Martins",
  "Trapiche da Barra",
  "Vergel do Lago",
];

export const Categorias = [
  "Bolinhas",
  "Géis",
  "Vibradores",
  "Dildos e Plugs",
  "Fetiche",
  "Massageadores",
  "Chocolates",
  "Para Menstruação",
  "Cuidados",
  "Anéis Penianos",
  "Outros",
];

export const Cidades = [
  "Maceió",
  "Rio Largo",
  "Satuba",
  "Santa Luzia do Norte",
];
