export const Bairros = [
  "Antares",
  "Barro Duro",
  "Bebedouro",
  "Benedito Bentes",
  "Bom Parto",
  "Chã de Bebedouro",
  "Centro",
  "Chã da Jaqueira",
  "Cidade Universitária",
  "Clima Bom",
  "Cruz das Almas",
  "Farol",
  "Feitosa",
  "Fernão Velho",
  "Garça Torta",
  "Gruta de Lourdes",
  "Guaxuma",
  "Ipioca",
  "Jacarecica",
  "Jacintinho",
  "Jaraguá",
  "Jardim Petrópolis",
  "Jatiúca",
  "Levada",
  "Mangabeiras",
  "Mutange",
  "Ouro Preto",
  "Pajuçara",
  "Pescaria",
  "Petrópolis",
  "Pinheiro",
  "Pitanguinha",
  "Ponta da Terra",
  "Ponta Grossa",
  "Ponta Verde",
  "Pontal da Barra",
  "Prado",
  "Riacho Doce",
  "Rio Novo",
  "Santa Amélia",
  "Santa Lúcia",
  "Santo Amaro",
  "Santos Dumont",
  "São Jorge",
  "Serraria",
  "Tabuleiro do Martins",
  "Trapiche da Barra",
  "Vergel do Lago",
];

export const Categorias = [
  "Vibros",
  "Plugs & Dildos",
  "Anéis e Masturbadores",
  "Cosméticos",
  "Cuidados",
  "Acessórios",
  "Lingeries",
  "Coleções",
  "Doces",
  "Outros",
];

export const Cidades = [
  "Maceió",
  "Rio Largo",
  "Satuba",
  "Santa Luzia do Norte",
];

export const Colmeia = [
  {
    name: "Pólen",
    price: "89,90",
    description: "Caixa Temática Mensal",
    link: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=2c93808479c587da0179c91fd87b0391",
  },
  {
    name: "Favo",
    price: "129,90",
    description: "Receba Mensalmente uma Caixa Personalizada",
    link: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=2c93808479abf8700179b144374901d9",
  },
  {
    name: "Abelha (Semestral)",
    price: "119,90",
    disc: "(6 x 119,90)",
    description: " Receba seis Caixas Personalizada",
    link: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=2c93808479c587f30179c92462bd0340",
  },
  {
    name: "Abelha",
    price: "119,90",
    disc: "(6 x 119,90)",
    description: " Receba seis Caixas Personalizada em meses alternados",
    link: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=2c93808479c587f30179c9237c57033d",
  },
  {
    name: "Abelha Rainha",
    price: "119,90",
    disc: "(12 x 119,90)",
    description: "Receba 12 Caixas Personalizada ao longo do ano",
    link: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=2c93808479c587bf0179c9254eb20347",
  },
  {
    name: "Melaço",
    price: "109,90",
    disc: "(1 x 1209,90)",
    description: " Pague por 11 caixas e receba 12! :D",
    link: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=2c93808479c587f30179c925d7f90344",
  },
];

export const novasCategorias = {
  VIBROS: [
    "BULLET",
    "CAPSULA",
    "COM CONTROLE",
    "DUPLO",
    "MASSAGEADOR",
    "PERSONAL",
    "RABBIT",
    "SUGADORES",
    "PENETRÁVEL",
    "PONTO G",
  ],

  "PLUGS E DILDOS": [
    "ANEL COMPANHEIRO",
    "DUPLO",
    "COM BASE",
    "SEM BASE",
    "COM VENTOSA",
    "COM RABINHO",
    "ESTIMULADOR DE PROSTATA",
    "PLUG BALL",
    "PLUG DE BORRACHA",
    "PLUG JOIA",
  ],

  "ANEIS E MASTURBADORES": [
    "ANEL COMPANHEIRO",
    "ANEIS STRETCH",
    "DEDEIRAS",
    "EGGS",
    "PARA PENIS",
  ],

  COMESTICOS: [
    "BEIJAVEIS",
    "LUBRIFICANTES",
    "PARA ANUS",
    "PARA PENIS",
    "PARA VULVA",
    "VIBRADOR LIQUIDO",
  ],

  CUIDADOS: ["HIGIENE", "PARA MENSTRUAÇÃO", "PRESERVATIVOS"],

  LINGERIES: ["CALCINHA", "CINTA-LIGAS", "HARNESS", "MEIAS"],

  ACESSORIOS: ["ALGEMAS", "CHICOTES", "CORDAS", "GRAMPO DE MAMILO"],

  COLEÇÕES: ["BENDITA VULVA", "MELLITIDEA"],

  DOCES: ["BOLOS", "BRIGADEIROS", "CHOCOLATES", "TRUFAS"],

  OUTROS: ["PARA LIMPEZA", "PILHAS", "TALCOS"],
};
